# -*- coding: utf-8 -*-
"""CodeAlpha_CreditScoringModel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uVtIjxhz-ujtXyveoPJd1FgvjlNHYMG8
"""

import pandas as pd

# Load dataset
df = pd.read_csv('credit_risk_dataset.csv')

# Show first 5 rows
df.head()

# Check dataset shape
print(df.shape)

# Column names
print(df.columns)

# Dataset information
df.info()

# Check missing values
df.isnull().sum()

# Fill numerical missing values with median

df['loan_int_rate'].fillna(df['loan_int_rate'].median(), inplace=True)

df['person_emp_length'].fillna(df['person_emp_length'].median(), inplace=True)

df.isnull().sum()

# Convert categorical columns into numbers

df = pd.get_dummies(df, drop_first=True)

# Features
X = df.drop('loan_status', axis=1)

# Target
y = df['loan_status']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

from sklearn.linear_model import LogisticRegression
import numpy as np
from sklearn.preprocessing import StandardScaler

# Create model
lr_model = LogisticRegression(max_iter=5000) # Increased max_iter

# Identify rows with NaN in X_train
nan_in_X_train = X_train.isnull().any(axis=1)
# Identify rows with NaN in y_train
nan_in_y_train = y_train.isnull()

# Get the boolean mask for rows to keep (no NaNs in X_train or y_train)
rows_to_keep = ~(nan_in_X_train | nan_in_y_train)

# Filter X_train and y_train to remove rows with NaNs
X_train_cleaned = X_train[rows_to_keep]
y_train_cleaned = y_train[rows_to_keep]

# Scale the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_cleaned)
X_test_scaled = scaler.transform(X_test) # Transform X_test using the scaler fitted on X_train

# Train model
lr_model.fit(X_train_scaled, y_train_cleaned)

y_pred_lr = lr_model.predict(X_test)

# Probability predictions for ROC-AUC
y_prob_lr = lr_model.predict_proba(X_test)[:, 1]

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report
)

print("Logistic Regression Results")
print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("Precision:", precision_score(y_test, y_pred_lr))
print("Recall:", recall_score(y_test, y_pred_lr))
print("F1-Score:", f1_score(y_test, y_pred_lr))
print("ROC-AUC:", roc_auc_score(y_test, y_prob_lr))

print(classification_report(y_test, y_pred_lr))

from sklearn.ensemble import RandomForestClassifier

# Create model
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

# Train model
rf_model.fit(X_train_cleaned, y_train_cleaned)

y_pred_rf = rf_model.predict(X_test)

# Probability predictions for ROC-AUC
y_prob_rf = rf_model.predict_proba(X_test)[:, 1]

print("Random Forest Results")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall:", recall_score(y_test, y_pred_rf))
print("F1-Score:", f1_score(y_test, y_pred_rf))
print("ROC-AUC:", roc_auc_score(y_test, y_prob_rf))

print(classification_report(y_test, y_pred_rf))

results = pd.DataFrame({
    'Model': ['Logistic Regression', 'Random Forest'],
    'Precision': [
        precision_score(y_test, y_pred_lr),
        precision_score(y_test, y_pred_rf)
    ],
    'Recall': [
        recall_score(y_test, y_pred_lr),
        recall_score(y_test, y_pred_rf)
    ],
    'F1-Score': [
        f1_score(y_test, y_pred_lr),
        f1_score(y_test, y_pred_rf)
    ],
    'ROC-AUC': [
        roc_auc_score(y_test, y_prob_lr),
        roc_auc_score(y_test, y_prob_rf)
    ]
})

print(results)

results.style.highlight_max(axis=0)